### PR TITLE
Remove duplicate key

### PR DESCRIPTION
**Pull request by ntwb**
Should fix failing tests in #3

### CODE REVIEW

**Comment by ben-eb** [comment]
The test failure is because eslint just released their new version and my config doesn't work with it. Need to use the shared config that I made, PR is welcome as I won't be at my computer today.

https://github.com/ben-eb/eslint-config-cssnano

Once I have all modules using that config I can upgrade it to support eslint 2.

**Comment by ntwb** [comment]
Ahhh, I just read the error in the Travis CI jobs, e.g. [Job #22.1](https://travis-ci.org/postcss/postcss-devtools/jobs/108852427#L758):

```
YAMLException: Cannot read config file: /home/travis/build/postcss/postcss-devtools/.eslintrc
Error: duplicated mapping key at line 70, column 18:
        modules: true
                     ^
```

As `modules: true` is declared twice in the `.eslintrc` config on lines [58](https://github.com/postcss/postcss-devtools/blob/master/.eslintrc#L58) and [70](https://github.com/postcss/postcss-devtools/blob/master/.eslintrc#L70)

Irrespective of the ESLint bump to 2.0.0 this duplicate should be removed from `.eslintrc` anyway yes?

**Comment by ben-eb** [comment]
The duplicate key was already removed in my shared config. Using that I get failures like this:

https://travis-ci.org/ben-eb/postcss-discard-unused/jobs/108912466

So I would prefer a patch that replaced this config with that one. :smile:

**Comment by ntwb** [comment]
I think https://github.com/ben-eb/eslint-config-cssnano/pull/1 will get the ball rolling for all these repo changes, I hope :smirk:

**Comment by ntwb** [comment]
Closing this, will not be needed when switching to `eslint-config-cssnano`

**Pull request closed without merging**
